version: '3'

tasks:
  run:
    desc: Run backend server
    cmds:
      - go run ./cmd/app

  build:
    desc: Build binary
    cmds:
      - go build -o bin/app ./cmd/app

  fmt:
    desc: Format Go code
    cmds:
      - gofmt -w .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  migrate-up:
    desc: Apply migrations
    cmds:
      - migrate -path {{.TASKFILE_DIR}}/migrations -database "{{.DB_URL}}" up
    vars:
      DB_URL: postgres://postgres:postgres@127.0.0.1:5432/chat?sslmode=disable

  migrate-down:
    desc: Rollback one migration
    cmds:
      - migrate -path {{.TASKFILE_DIR}}/migrations -database "{{.DB_URL}}" down 1
    vars:
      DB_URL: postgres://postgres:postgres@127.0.0.1:5432/chat?sslmode=disable

  docker-up:
    desc: Start PostgreSQL
    cmds:
      - docker compose up -d

  docker-down:
    desc: Stop PostgreSQL
    cmds:
      - docker compose down
