version: '3'

tasks:

  migrate-up:
    desc: Apply all migrations
    cmds:
      - docker exec -i chat-db-1 psql -U chat -d chat < migrations/001_users.up.sql
      - docker exec -i chat-db-1 psql -U chat -d chat < migrations/002_create_messages.up.sql

  migrate-down:
    desc: Rollback all migrations
    cmds:
      - docker exec -i chat-db-1 psql -U chat -d chat < migrations/002_create_messages.down.sql
      - docker exec -i chat-db-1 psql -U chat -d chat < migrations/001_users.down.sql

  migrate-drop-all:
    desc: Drop ALL tables
    cmds:
      - docker exec -i chat-db-1 psql -U chat -d chat -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"

  migrate-reset:
    desc: Reset database
    cmds:
      - task: migrate-drop-all
      - task: migrate-up

  migrate-status:
    desc: Show tables
    cmds:
      - docker exec -i chat-db-1 psql -U chat -d chat -c "\\dt"